### PR TITLE
chore: Initial project

### PR DESCRIPTION
**Pull request by PedroChaparro**
Includes: 

- Base scala project (No http server) 
- Sample files and tests (`fruit` package)
- Instructions to run the tests and generate coverage reports. 
- Basic docker file to build and run the app. Note that the size of the image was reduced from **~730MB** to **~156MB** using an alpine-based image instead of a debian-based one.

### CODE REVIEW

**Comment by PedroChaparro** [comment]
@shoriwe Hi, can you take a look at this? Let me know if you need anything else so I can include it before merging this to the main branch.

**Review by shoriwe — COMMENTED** [review]
Great work @PedroChaparro, Squash and merge please

**Review by shoriwe — COMMENTED** [review]
.

**Review by shoriwe — APPROVED** [review]
Approved 🚀🚀🚀

**Comment by PedroChaparro** [comment]
> Approved 🚀🚀🚀

Will you add the `testing`, `tagging`, `release` and `coverage` workflows? I think I can add the `testing` one since it doesn't depend on any tokens / credentials.

**Pull request merged**
