### PR TITLE
fix(ci): Update test pipeline

### PR DESCRIPTION
**Pull request by PedroChaparro**
Includes: 

- Remove non-existent input. 
- Fix JDK version in the build job. 
- Skip tests in the build job.

### CODE REVIEW

**Comment by shoriwe** [comment]
Does this was already tested in the other PR?

You can check it works by committing this change to this [PR-6](https://github.com/hawks-atlanta/metadata-scala/pull/6) first

**Comment by PedroChaparro** [comment]
> Does this was already tested in the other PR?

Thanks! It's ready now. As you can see in #6, the test job fails when any of the tests fails.

**Comment by PedroChaparro** [comment]
@shoriwe The `dev` branch is not protected. I can merge without your approval.

**Review by shoriwe — APPROVED** [review]
Great job @PedroChaparro, approved 🚀🚀🚀🚀🚀
PS: Squash and merge

**Comment by PedroChaparro** [comment]
> PS: Squash and merge

Should I create a PR from `dev` to `main` now?

**Comment by shoriwe** [comment]
@PedroChaparro Yes, you should

**Pull request merged**
