### PR TITLE
Feat: Save metadata

### LINKED ISSUE #26: feat: (POST) Save metadata for a new file or directory

### PR DESCRIPTION
**Pull request by PedroChaparro**
Close #26. 

Includes: 
- Configure and format files with `scala-fmt`
- Setup HTTP server with `Cask`
- Setup schema validations with `Accord`
- Remove sample packages (fruits). 
- Endpoint to save metadata. 
- Test the endpoint with `Junit` and `Assured`
- Update status codes and field names in the `openapi` spec.
- Add some example request in the `docs/rest` folder. 

Sorry for the amount of changes 🫠

### CODE REVIEW

**Review by Woynert — COMMENTED** [review]
I'm not sure I'm doing something wrong but the app seems to exit just after starting. So I couldn't test the endpoint.

```
nix:/misc/dev/workgit/metadata-scala feat/save-metadata$ sbt run
[info] welcome to sbt 1.9.3 (N/A Java 19.0.2)
[info] loading settings for project metadata-scala-build from assembly.sbt,plugins.sbt ...
[info] loading project definition from /misc/dev/workgit/metadata-scala/project
[info] loading settings for project root from build.sbt ...
[info] set current project to metadata (in build file:/misc/dev/workgit/metadata-scala/)
[warn] there's a key that's not used by any other settings/tasks:
[warn]
[warn] * root / idePackagePrefix
[warn]   +- /misc/dev/workgit/metadata-scala/build.sbt:7
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key

Multiple main classes detected. Select one to run:
 [1] org.hawksatlanta.metadata.Main
 [2] org.hawksatlanta.metadata.shared.infrastructure.CaskHTTPRouter

Enter number: 1
[info] running org.hawksatlanta.metadata.Main
Aug 31, 2023 6:24:40 PM org.flywaydb.core.internal.license.VersionPrinter printVersionOnly
INFO: Flyway Community Edition 9.16.0 by Redgate
Aug 31, 2023 6:24:40 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO: See release notes here: https://rd.gt/416ObMi
Aug 31, 2023 6:24:40 PM org.flywaydb.core.internal.license.VersionPrinter printVersion
INFO:
Aug 31, 2023 6:24:40 PM org.flywaydb.core.internal.database.base.BaseDatabaseType createDatabase
INFO: Database: jdbc:postgresql://localhost:5432/metadata (PostgreSQL 15.4)
Aug 31, 2023 6:24:40 PM org.flywaydb.core.internal.command.DbValidate validate
INFO: Successfully validated 1 migration (execution time 00:00.022s)
Aug 31, 2023 6:24:41 PM org.flywaydb.core.internal.command.DbMigrate migrateGroup
INFO: Current version of schema "public": 1
Aug 31, 2023 6:24:41 PM org.flywaydb.core.internal.command.DbMigrate logSummary
INFO: Schema "public" is up to date. No migration necessary.
0 migrations were successfully executed.SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
Aug 31, 2023 6:24:41 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.1.0.Final
[success] Total time: 2 s, completed Aug 31, 2023, 6:24:41 PM
```

**Comment by PedroChaparro** [comment]
> I'm not sure I'm doing something wrong, but the app seems to exit just after starting. Can't test the endpoint.
> 

You're right. I haven´t use the `sbt run` command to run the app. It works if you run it from IntelliJ. 

It's weird because there wasn't any problem with the migrations but the command doesn't keep the server running. I'll check that.

**Comment by PedroChaparro** [comment]
@Woynert Hi 👋🏽. Try with the following commands: 

1. Enter the `sbt` interactive mode: 

```bash
sbt
```

2. Start the app and listen for changes in the source: 

```bash
~runMain org.hawksatlanta.metadata.Main
```

Let me know if that works for you.

**Review by Woynert — APPROVED** [review]
:balloon: Great job!

My only complain would be against asserting the response messages.

But I think it's fine as it is!

**Comment by PedroChaparro** [comment]
> My only complain would be against asserting the response messages.

You mean asserting in the tests, right? I agree with you, maybe I can ignore the generic fields like the "error" boolean and the "message" string and just assert the important fields.

Thanks for reviewing the PR 🙇🏽‍♂️ it was a large one.

**Comment by Woynert** [comment]
@PedroChaparro Yes, the "message" string field could be ignored in future tests

**Pull request merged**
